# project definitions
project: qgis
audience: designers
product: doc
platform: all
version: all
output: web
#destination: _site
topnav_title: An Introduction to QGIS
homepage_title: QGIS - an introduction
site_title: An Introduction to QGIS
project_folder: qgis
company_name: Fish & Whistle
footer_image_location: ../common_images/company_logo.png
github_editme_path: paleolimbot/QGIS-Intro-Course/edit/gh-pages
# disqus_shortname: idrbwjekyll
# variables

sidebar_tagline: Contents
sidebar_version: January 17, 2016
theme_file: theme-blue.css
pdf_file_name: qgis_2016-01-17_pdf.pdf

port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/qgis_writers*

# same for all
host: 127.0.0.1
feedback_email: dewey@fishandwhistle.net

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

